// Typeahead
$(function () {
    var dishes = [
        "Green Smoothy",
        "Veggie Salad",
        "Tart",
        "Vanila Choco Cake",
        "Vanila Choco",
        "Healthy Diet",
        "Tasty n Cruncy",
        "Healthy Drink",
        "Cakes",
        "Fruti Cup-cakes",
        "Veggie Breakfast",
        "Spicy Pasta",
        "Spicy Treat",
        "Deserts",
        "Icecream",
        "Ice-cream",
        "RB-Bry Lemon Tart",
        "Fruit jelly",
        "Mango Jelly",
        "Hot Coffy Sweet Pastry",
        "Hot n Sweet",
        "Keep Warm",
        "Tamato Soup",
        "Soup",
        "Desert Dink",
        "Hot Choco Pudding",
        "Pudding",
        "Cheesy Treat",
        "Cheezy Pizza",
        "Nurition Rich",
        "Nutri Plate",
        "Natural Friuts",
        "Fresh Mangos",
        "Indian Sweets",
        "Sesame Lado",
        "Lado",
        "Mango",
        "Desert Icecream",
        "Mango Ice Cream",
        "Meal",
        "Gift Basket",
        "Lunch Thali",
        "Fruty Salad",
        "Fresh Fruits",
    ];
    $("#search_dish").typeahead({ source: dishes });
    $("#search_dish_block").typeahead({ source: dishes });
    $("#search_dish_req").typeahead({ source: dishes });
});
